CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(70)
);

CREATE TABLE PRODUTO(
	ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
	PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT REFERENCES CLIENTE(ID_CLIENTE),
	DATA_PEDIDO TIMESTAMP,
	TOTAL NUMERIC(20,2) 
);

CREATE TABLE ITEM_PEDIDO(
	ID_ITEM_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	ID_PEDIDO INT REFERENCES PEDIDO(ID_PEDIDO),
	ID_PRODUTO INT REFERENCES PRODUTO(ID_PRODUTO),
	QUANTIDADE INT DEFAULT 1
);